# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
title = "ROS2 Python Custom OmniGraph Node"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}
"isaacsim.ros2.bridge" = {}

# define the Python module that the extension provides
[[python.module]]
name = "custom.python.ros2_node"

[settings]
exts."custom.python.ros2_node".timeout = 5

